-- ***********************************************************************
-- Script: V3__agregar_tabla_customers_orders.sql
-- Descripción: Crea las tablas customers, purchase_orders y line_items,
-- incluyendo sus restricciones de claves primarias y foráneas.
-- Autor: TuNombre
-- Fecha: 2025-05-20
-- ***********************************************************************

-- =========================
-- 1. Tabla de clientes
-- =========================
CREATE TABLE customers (
                           id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           name VARCHAR(64),
                           email VARCHAR(64),
                           version INTEGER,
                           CONSTRAINT pk_customers PRIMARY KEY (id)
);

-- =========================
-- 2. Tabla de órdenes de compra
-- =========================
CREATE TABLE purchase_orders (
                                 id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                 customer_id INTEGER,
                                 total INTEGER,
                                 status SMALLINT,
                                 placed_on TIMESTAMP,
                                 delivered_on TIMESTAMP,
                                 CONSTRAINT pk_purchase_orders PRIMARY KEY (id)
);

-- =========================
-- 3. Tabla de ítems de cada orden
-- =========================
CREATE TABLE line_items (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            order_id INTEGER,
                            quantity INTEGER,
                            isbn VARCHAR(64),
                            CONSTRAINT pk_line_items PRIMARY KEY (id)
);

-- =========================
-- 4. Restricciones de claves foráneas
-- =========================
ALTER TABLE purchase_orders
    ADD CONSTRAINT fk_orders_customers
        FOREIGN KEY (customer_id)
            REFERENCES customers (id);

ALTER TABLE line_items
    ADD CONSTRAINT fk_line_items_orders
        FOREIGN KEY (order_id)
            REFERENCES purchase_orders (id);

ALTER TABLE line_items
    ADD CONSTRAINT fk_line_items_books
        FOREIGN KEY (isbn)
            REFERENCES books (isbn);
